# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

plist = []

def pentagonal(number):
    return int((number * (3 * number - 1))/2)

for n in range(1,20000):
    plist.append(pentagonal(n))

for n in range(len(plist)-1):
    for x in range(n+1,len(plist)):
        if (plist[n] + plist[x] in plist):
            if (plist[x] - plist[n] in plist):
                print(n,x)
