# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

t = 285
p = 165
h = 143
tlist = []
plist = []
hlist = []

def triangle(number):
    return int((number * (number + 1))/2)

def pentagonal(number):
    return int((number * (3 * number - 1))/2)
    
def hexagonal(number):
    return int(number * (2 * number - 1))

while True:
    t += 1
    p += 1
    h += 1
    tlist.append(triangle(t))
    plist.append(pentagonal(p))
    hlist.append(hexagonal(h))
    if triangle(t) in plist and triangle(t) in hlist:
        print(triangle(t))
        break
    elif pentagonal(p) in tlist and pentagonal(p) in hlist:
        print(pentagonal(p))
        break
    elif hexagonal(h) in tlist and hexagonal(h) in plist:
        print(hexagonal(h))
        break
